package SEFinalProject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FinalProjectGui {
    private JPanel panel1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public static class BankAccount extends JPanel implements ActionListener {

        JButton debit = new JButton("Debit");

        JButton credit = new JButton("Credit");

        JButton exit = new JButton("Exit");

        TextField t1, t2, output; // text fields

        Label debitAccount, creditAccount, balanceAmount; // labels

        double accountBalance = 0.0;

        public BankAccount(JFrame frame) {

            /*

             *

             * creating label , setting boundaries and adding to frame

             */

            debitAccount = new Label(" Debit Amount :");

            debitAccount.setBounds(50, 70, 115, 50);

            frame.add(debitAccount);

            /*

             *

             * creating text box and setting boundaries and adding to frame

             */

            t1 = new TextField("");

            t1.setBounds(165, 70, 100, 50);

            frame.add(t1);

            /*

             *

             * creating label , seting boundaries and adding to frame

             */

            creditAccount = new Label(" Credit Amount :");

            creditAccount.setBounds(50, 180, 115, 50);

            frame.add(creditAccount);

            /*

             *

             * creating text box and seting boundaries and adding to frame

             */

            t2 = new TextField("");

            t2.setBounds(165, 180, 100, 50);

            frame.add(t2);

            debit.addActionListener(this);

            debit.setBounds(150, 250, 150, 30);

            frame.add(debit);


            credit.addActionListener(this);

            credit.setBounds(300, 250, 150, 30);

            frame.add(credit);





            /*

             *

             * creating label , setting boundaries and adding to frame

             */

            balanceAmount = new Label(" Balance Amount :");

            balanceAmount.setBounds(300, 180, 100, 50);

            frame.add(balanceAmount);





            /*

             *

             * creating text box and setting boundaries and adding to frame

             */

            output = new TextField("");

            output.setBounds(400, 180, 100, 50);

            frame.add(output);


            exit.addActionListener(this);

            exit.setBounds(450, 250, 150, 30);
            ;

            frame.add(exit);

        }

        public static void main(String[] args) {

            JFrame frame = new JFrame();

            frame.getContentPane().add(new BankAccount(frame));

            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            frame.setSize(700, 400);

            frame.setVisible(true);

        }

        public void actionPerformed(ActionEvent e) {

            if (e.getActionCommand().equals("Debit")) {

                System.out.println("Debit has been clicked");

                String balanceAmount = t1.getText();

                double debitAmount = Double.parseDouble(balanceAmount);

                accountBalance = accountBalance + debitAmount;

                output.setText(String.valueOf(accountBalance));

                t1.setText("");

            } else if (e.getActionCommand().equals("Credit")) {

                System.out.println("Debit has been clicked");

                String balanceAmount = t2.getText();

                double creditAmount = Double.parseDouble(balanceAmount);

                accountBalance = accountBalance - creditAmount;

                output.setText(String.valueOf(accountBalance));

                t2.setText("");

            } else if (e.getActionCommand().equals("Exit")) {

                System.exit(0);

            }

        }

    }//class BankAccount ends
}
